[development]
address = "127.0.0.1"
port = 9600
limits = { forms = 32768 }

# [production]
# address = "0.0.0.0"
# port = 8000
# #workers = [number of cpus * 2]
# keep_alive = 5
# log = "critical"
# #secret_key = [randomly generated at launch]
# limits = { forms = 32768 }