@test_url = http://localhost:9600
@online_url = http:://10.0.6.43:9600
@port = 8000
@url = localhost

### 入口文件测试
curl http://127.0.0.1:9600



### rust 入口文件测试
curl {{test_url}}


### rust 获取头部header 
curl {{test_url}}/api/auth/auth/ -u "admin:admin"

### rocket 获取cookie
curl {{test_url}}/api/cookie  -b name="hzjsea"


### rocket 
curl {{test_url}}/api/2

### 
curl {{test_url}}/api/content/

### just_fail  back 406
curl {{test_url}}/api/status

### body data
curl {{test_url}}/api/people

### form data
POST  http://localhost:8000/api/todo HTTP/1.1
Content-Type: application/x-www-form-urlencoded

type=true&description="hzjsea"

### authen Action
POST {{test_url}}/users/host/auth HTTP/1.1
Content-Type: application/json

{
    "action": "check_auth",
    "source_addr": "helloworld",
     "data": {
         "status": 200,
         "authenticator_source":[0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16]
      }
}

###
POST {{test_url}}/users/host/auth HTTP/1.1
Content-Type: application/json

{
    "action":"check_auth",
    "data": {
            "authenticator_source":"6ZT7n9vCm5LLEfgMpsHDbw==",
            "timestamp":331155752
     },
     "source_addr":"OTAwMDAx"
}

###a
POST {{online_url}}/users/host/auth HTTP/1.1
Content-Type: application/json

{
    "action":"check_auth",
    "data": {
            "authenticator_source":"6ZT7n9vCm5LLEfgMpsHDbw==",
            "timestamp":331155752
     },
     "source_addr":"OTAwMDAx"
}

